"""
Jawab Outreach Message Customizer
==================================
Reads 02_Outreach_and_Data/04_AUDIT_RESULTS.csv and automatically generates
highly personalized, structured WhatsApp and IG DM scripts for each clinic.

Usage:
    python 04_System_and_Skills/outreach_customizer.py
"""

import csv
import os

AUDIT_CSV = os.path.join(os.path.dirname(__file__), "..", "02_Outreach_and_Data", "04_AUDIT_RESULTS.csv")
OUTPUT_MD = os.path.join(os.path.dirname(__file__), "..", "02_Outreach_and_Data", "05_GENERATED_OUTREACH_MESSAGES.md")

def get_whatsapp_template(name, doctor, specialty, phone, wa_path, rating, review_count, notes, score):
    # Determine greetings
    greeting_name = f"Dr. {doctor}" if doctor and "Dr." not in doctor else doctor if doctor else f"{name} Team"
    
    # Analyze main pain point
    notes_lower = notes.lower()
    
    # 1. Broken website pain point
    if "website down" in notes_lower or "website suspended" in notes_lower or "unreachable" in notes_lower:
        pain_desc = "your website path is currently suspended or unreachable on mobile"
        angle_desc = "when a website goes down, patients booking high-ticket treatments instantly click the next clinic on Google Maps."
        call_to_action = "I set up a 45-second mock-up showing how Jawab recovers these bouncing website patients. Can I drop the link here?"
    
    # 2. Slow website pain point
    elif "very slow" in notes_lower or "website slow" in notes_lower:
        pain_desc = "your website on mobile is loading slow, creating a conversion bottleneck"
        angle_desc = "in Dubai's competitive market, a 4-second loading delay causes up to 40% of mobile searchers to drop off."
        call_to_action = "I have a quick mobile speed diagnostic showing where the leakage is. Mind if I share it?"
        
    # 3. Missing WhatsApp Business path
    elif "no direct whatsapp" in notes_lower or "whatsapp path unclear" in notes_lower:
        pain_desc = "there's no direct, one-click WhatsApp Business path exposed to patients on mobile"
        angle_desc = "most premium patients in the UAE expect to book cosmetic or implant appointments on WhatsApp rather than calling a landline."
        call_to_action = "I built a quick WhatsApp booking prototype for your clinic. Can I send you a 60-second Loom of how it works?"
        
    # 4. Low reviews / Rating gaps
    elif review_count != "N/A" and review_count != "" and int(review_count) < 150:
        pain_desc = f"your Google Maps reviews stand at {review_count} — leaving an opportunity to build trust wrapper vs competitors"
        angle_desc = "high-ticket veneer and implant patients actively compare review counts before picking a clinic."
        call_to_action = "We have an automated post-treatment review booster. Can I send you the case study showing how we doubled review velocity for a similar clinic?"
        
    # Default high-ticket leak recovery
    else:
        pain_desc = "your front desk has a high potential for response leakage on high-ticket inquiries during peak hours"
        angle_desc = "even a 5-minute response delay on WhatsApp causes high-intent patients to message the next provider."
        call_to_action = "I have a 60-second video showing how Jawab recovers lost patient consults automatically. Want me to send the link?"

    body = f"""### {name}
* **Channel:** {"WhatsApp to " + phone if "Direct" in wa_path else "Instagram DM / Website Contact"}
* **Lead Score:** {score}/100
* **Target Phone/Contact:** {phone}
* **Specialty Focus:** {specialty or "Cosmetic & Implants"}

```text
Hi {greeting_name} — quick note for the clinic team.

I was looking at {name}'s public patient pathways on mobile and noticed {pain_desc}. 

Usually, {angle_desc}

I built Jawab — a bilingual (Arabic-English) patient recovery system specifically calibrated for UAE dental clinics. It integrates with your phone system and WhatsApp to catch missed calls, delayed replies, and post-consult drop-offs, moving them back to booking.

{call_to_action}

Guarantee: If Jawab doesn't recover at least 5 premium patient opportunities in your first 14 days, you pay nothing.

Best,
Adam
```

---
"""
    return body

def main():
    if not os.path.exists(AUDIT_CSV):
        print(f"[!] Audit CSV not found at: {AUDIT_CSV}")
        return
        
    print(f"[*] Reading leads from {AUDIT_CSV}...")
    
    with open(AUDIT_CSV, encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        leads = list(reader)
        
    markdown_content = f"""# Generated Outreach Messages — {len(leads)} Clinics
Auto-generated by Jawab Customizer based on live Revenue Leak scores.

---

"""
    
    for i, lead in enumerate(leads):
        name = lead.get("Clinic Name", "Unknown")
        doctor = lead.get("Doctor", "")
        specialty = lead.get("Specialty", "")
        phone = lead.get("WhatsApp Path", "").replace("Direct: ", "").replace("Mobile (likely WhatsApp): ", "")
        wa_path = lead.get("WhatsApp Path", "")
        rating = lead.get("Google Rating", "")
        review_count = lead.get("Review Count", "")
        notes = lead.get("Notes", "")
        score = lead.get("Revenue Leak Score", "0")
        
        markdown_content += get_whatsapp_template(name, doctor, specialty, phone, wa_path, rating, review_count, notes, score)
        
    with open(OUTPUT_MD, "w", encoding="utf-8") as f:
        f.write(markdown_content)
        
    print(f"[+] Successfully generated customized outreach messages!")
    print(f"[+] Output saved to: {os.path.abspath(OUTPUT_MD)}")

if __name__ == "__main__":
    main()
